#!/usr/bin/env bash
# This script loop from 1 - 10 using while loop
# Display "bad luck" for the 4th interation
# Display "good luck" for the 8th interation
# Display "Best School" for the other interations

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi

	((counter++))
done
