#!/usr/bin/env bash
# write a bash script that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

file_list=$(ls)

filtered_list=""
for file in $filtered_list; do
	filtered_list=$(echo "file" | cut -d '-' -f 2)
done
